---
name: build/test/publish workflow.

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  test-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml 
      
    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/1043833862392/locations/global/workloadIdentityPools/identity-pool/providers/oidc-provider'
        service_account: 'oauthuserinfo@appspot.gserviceaccount.com'

    - uses: 'google-github-actions/deploy-appengine@v2'
      with:
        project_id: oauthuserinfo
        working_directory: target/oauthUserInfo-1.0
        deliverables: WEB-INF/appengine-web.xml
      
...
